AVAILABLE_LOCATIONS = {
  berlin: { short: "berlin", name: "Berlin", currency: "EUR", country_long: "Germany", country_short: "DE", lat: "52.5167", lng: "13.3833" },
  london: { short: "london", name: "London", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "51.5072", lng: "0.1275" },
  new_york_city: { short: "newyork", name: "New York City", currency: "USD", country_long: "United States", country_short: "US", lat: "40.7127", lng: "-74.0059" }
  #san_francicso: { short: "sanfrancisco", name: "San Francisco", currency: "USD", country_long: "United States", country_short: "US", lat: "37.77493", lng: "-122.4167" }

  # amsterdam: { name: "Amsterdam", currency: "EUR", country_long: "The Netherlands", country_short: "NL", lat: "52.3667", lng: "4.9000" },
  # atlanta: { name: "Atlanta", currency: "USD", country_long: "United States", country_short: "US", lat: "33.7550", lng: "-84.3900" },
  # austin: { name: "Austin", currency: "USD", country_long: "United States", country_short: "US", lat: "30.2500", lng: "-97.7500" },
  # belfast: { name: "Belfast, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "54.5970", lng: "-5.9300" },
  # birmingham_uk: { name: "Birmingham, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "52.4831", lng: "1.8936" },
  # boston: { name: "Boston", currency: "USD", country_long: "United States", country_short: "US", lat: "42.3581", lng: "-71.0636" },
  # bristol_uk: { name: "Bristol, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "51.4500", lng: "-2.5833" },
  # brussels: { name: "Brussels", currency: "EUR", country_long: "Belgium", country_short: "BE", lat: "50.8500", lng: "4.3500" },
  # chicago: { name: "Chicago", currency: "USD", country_long: "United States", country_short: "US", lat: "41.8819", lng: "-87.6278" },
  # cologne: { name: "Cologne", currency: "EUR", country_long: "Germany", country_short: "DE", lat: "50.9364", lng: "6.9528" },
  # dallas: { name: "Dallas", currency: "USD", country_long: "United States", country_short: "US", lat: "37.7833", lng: "-96.7967" },
  # dublin: { name: "Dublin", currency: "EUR", country_long: "Ireland", country_short: "IE", lat: "53.3478", lng: "-6.2597" },
  # frankfurt: { name: "Frankfurt", currency: "EUR", country_long: "Germany", country_short: "DE", lat: "50.1167", lng: "8.6833" },
  # hamburg: { name: "Hamburg", currency: "EUR", country_long: "Germany", country_short: "DE", lat: "53.5653", lng: "10.0014" },
  # helsinki: { name: "Helsinki", currency: "EUR", country_long: "Finland", country_short: "FI", lat: "60.1708", lng: "24.9375" },
  # houston: { name: "Houston", currency: "USD", country_long: "United States", country_short: "US", lat: "29.7628", lng: "-95.3831" },
  # leeds: { name: "Leeds, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "53.7997", lng: "-1.5492" },
  # liverpool: { name: "Liverpool, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "53.4000", lng: "-3.0000" },
  # los_angeles: { name: "Los Angeles", currency: "USD", country_long: "United States", country_short: "US", lat: "34.0500", lng: "-118.2500" },
  # manchester_uk: { name: "Manchester, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "53.4667", lng: "-2.2333" },
  # munich: { name: "Munich", currency: "EUR", country_long: "Germany", country_short: "DE", lat: "48.1333", lng: "11.5667" },
  # nashville: { name: "Nashville", currency: "USD", country_long: "United States", country_short: "US", lat: "36.1667", lng: "-86.7833" },
  # paris: { name: "Paris", currency: "EUR", country_long: "France", country_short: "FR", lat: "48.8567", lng: "2.3508" },
  # philadelphia: { name: "Philadelphia", currency: "USD", country_long: "United States", country_short: "US", lat: "39.9500", lng: "-75.1667" },
  # portland: { name: "Portland", currency: "USD", country_long: "United States", country_short: "US", lat: "45.5200", lng: "-122.6819" },
  # seattle: { name: "Seattle", currency: "USD", country_long: "United States", country_short: "US", lat: "47.6097", lng: "-122.3331" },
  # sheffield: { name: "Sheffield, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", lat: "53.3836", lng: "-1.4669" },
  # stuttgart: { name: "Stuttgart", currency: "EUR", country_long: "Germany", country_short: "DE", lat: "48.7833", lng: "9.1833" },
  # vienna: { name: "Vienna", currency: "EUR", country_long: "Austria", country_short: "AT", lat: "48.2000", lng: "16.3667" },
  # washington_dc: { name: "Washington DC", currency: "USD", country_long: "United States", country_short: "US", lat: "38.8951", lng: "-77.0367" }
}
