AVAILABLE_LOCATIONS = {
  berlin: { name: "Berlin", currency: "EUR", country_long: "Germany", country_short: "DE", latitude: "52.5167", longitude: "13.3833" },
  london: { name: "London", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "51.5072", longitude: "0.1275" },
  new_york_city: { name: "New York City", currency: "USD", country_long: "United States", country_short: "US", latitude: "40.7127", longitude: "-74.0059" },
  amsterdam: { name: "Amsterdam", currency: "EUR", country_long: "The Netherlands", country_short: "NL", latitude: "52.3667", longitude: "4.9000" },
  atlanta: { name: "Atlanta", currency: "USD", country_long: "United States", country_short: "US", latitude: "33.7550", longitude: "-84.3900" },
  austin: { name: "Austin", currency: "USD", country_long: "United States", country_short: "US", latitude: "30.2500", longitude: "-97.7500" },
  belfast: { name: "Belfast, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "54.5970", longitude: "-5.9300" },
  birmingham_uk: { name: "Birmingham, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "52.4831", longitude: "1.8936" },
  boston: { name: "Boston", currency: "USD", country_long: "United States", country_short: "US", latitude: "42.3581", longitude: "-71.0636" },
  bristol_uk: { name: "Bristol, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "51.4500", longitude: "-2.5833" },
  brussels: { name: "Brussels", currency: "EUR", country_long: "Belgium", country_short: "BE", latitude: "50.8500", longitude: "4.3500" },
  chicago: { name: "Chicago", currency: "USD", country_long: "United States", country_short: "US", latitude: "41.8819", longitude: "-87.6278" },
  cologne: { name: "Cologne", currency: "EUR", country_long: "Germany", country_short: "DE", latitude: "50.9364", longitude: "6.9528" },
  dallas: { name: "Dallas", currency: "USD", country_long: "United States", country_short: "US", latitude: "37.7833", longitude: "-96.7967" },
  dublin: { name: "Dublin", currency: "EUR", country_long: "Ireland", country_short: "IE", latitude: "53.3478", longitude: "-6.2597" },
  frankfurt: { name: "Frankfurt", currency: "EUR", country_long: "Germany", country_short: "DE", latitude: "50.1167", longitude: "8.6833" },
  hamburg: { name: "Hamburg", currency: "EUR", country_long: "Germany", country_short: "DE", latitude: "53.5653", longitude: "10.0014" },
  helsinki: { name: "Helsinki", currency: "EUR", country_long: "Finland", country_short: "FI", latitude: "60.1708", longitude: "24.9375" },
  houston: { name: "Houston", currency: "USD", country_long: "United States", country_short: "US", latitude: "29.7628", longitude: "-95.3831" },
  leeds: { name: "Leeds, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "53.7997", longitude: "-1.5492" },
  liverpool: { name: "Liverpool, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "53.4000", longitude: "-3.0000" },
  los_angeles: { name: "Los Angeles", currency: "USD", country_long: "United States", country_short: "US", latitude: "34.0500", longitude: "-118.2500" },
  manchester_uk: { name: "Manchester, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "53.4667", longitude: "-2.2333" },
  munich: { name: "Munich", currency: "EUR", country_long: "Germany", country_short: "DE", latitude: "48.1333", longitude: "11.5667" },
  nashville: { name: "Nashville", currency: "USD", country_long: "United States", country_short: "US", latitude: "36.1667", longitude: "-86.7833" },
  paris: { name: "Paris", currency: "EUR", country_long: "France", country_short: "FR", latitude: "48.8567", longitude: "2.3508" },
  philadelphia: { name: "Philadelphia", currency: "USD", country_long: "United States", country_short: "US", latitude: "39.9500", longitude: "-75.1667" },
  portland: { name: "Portland", currency: "USD", country_long: "United States", country_short: "US", latitude: "45.5200", longitude: "-122.6819" },
  san_francicso: { name: "San Francisco", currency: "USD", country_long: "United States", country_short: "US", latitude: "32.7758", longitude: "-122.4167" },
  seattle: { name: "Seattle", currency: "USD", country_long: "United States", country_short: "US", latitude: "47.6097", longitude: "-122.3331" },
  sheffield: { name: "Sheffield, UK", currency: "GBP", country_long: "United Kingdom", country_short: "UK", latitude: "53.3836", longitude: "-1.4669" },
  stuttgart: { name: "Stuttgart", currency: "EUR", country_long: "Germany", country_short: "DE", latitude: "48.7833", longitude: "9.1833" },
  vienna: { name: "Vienna", currency: "EUR", country_long: "Austria", country_short: "AT", latitude: "48.2000", longitude: "16.3667" },
  washington_dc: { name: "Washington DC", currency: "USD", country_long: "United States", country_short: "US", latitude: "38.8951", longitude: "-77.0367" }
}
