development:
  secret_key_base: 674f0c4008a10573237fc9c5c4a58f26d53360073c0babad365fc95e2e7b11459e2f7e3b1ebdace228a83b049c5707c22460338825d29ba990b66dd1e8ccfab5
  stripe_secret_key: sk_test_4WOUaqdQWTHVXWePtrD2eCCd
  stripe_publishable_key: pk_test_4WOUe7RQsT8jb3x2EBTrF2Ib
  twilio_account_sid: ACd0b05c94cb01242fcebd1e5e2bbd5180
  twilio_token: 3c96ad19de611ad44498df874ccaf93f
  twilio_from: +15005550006

  mailchimp_api_key: b0b9df2b00309d67f7839a3c9571bafc-us8
  mailchimp_newsletter_id: ff3a55a15c
  mailchimp_press_id: ff3a55a15c
  mailchimp_artist_id: ff3a55a15c
  mailchimp_customer_id: ff3a55a15c
  
  balanced_api_key:  ak-test-1DC6r3MCUT8rUhlMjkcw3UrB8EDgiUg6P

test:
  secret_key_base: d07b88575d1e42527b3b02a43cb416e29c8b9af03e359075892c8bd9dc6d6c67d138234832e53900af4eb2ad618423fad332e38d75293dbfa75dfec1acf99d25
  twilio_account_sid: abc
  twilio_token: abc
  twilio_from: +15005550006

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_from: <%= ENV["TWILIO_FROM"] %>
  
  mailchimp_api_key: b0b9df2b00309d67f7839a3c9571bafc-us8
  mailchimp_newsletter_id: c1377d49f5
  mailchimp_press_id: 150898c659
  mailchimp_artist_id: f38b96fdb5
  mailchimp_customer_id: ce0be5cff0
  
  balanced_api_key:  ak-test-1DC6r3MCUT8rUhlMjkcw3UrB8EDgiUg6P  